In [4]:
import pandas as pd
import duckdb
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("../data/players_data_light-2025_2026.csv").convert_dtypes()


df.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,25,2000,37,30,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,2,Jerome Abbey,eng ENG,MF,Wolves,eng Premier League,16,2009,1,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,3,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,20,2006,3,2,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,4,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,20,2006,22,4,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,5,Himad Abdelli,dz ALG,MF,Marseille,fr Ligue 1,26,1999,8,1,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [8]:
cleaned_df = df[df['90s'] >= 5.0].copy()

liga_query = """
    SELECT Comp, COUNT(*) as AntalSpelare
    FROM cleaned_df
    GROUP BY Comp
    ORDER BY AntalSpelare DESC
"""
liga_stats = duckdb.query(liga_query).to_df()


print(f"Antal spelare från början: {len(df)}")
print(f"Antal spelare efter rensning: {len(cleaned_df)}\n")
print("Antal rensade spelare per liga:")
print(liga_stats)


cleaned_df.head()

Antal spelare från början: 2839
Antal spelare efter rensning: 2005

Antal rensade spelare per liga:
                 Comp  AntalSpelare
0          it Serie A           440
1          es La Liga           428
2  eng Premier League           405
3          fr Ligue 1           373
4       de Bundesliga           359

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,25,2000,37,30,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,4,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,20,2006,22,4,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
5,6,Himad Abdelli,dz ALG,MF,Angers,fr Ligue 1,26,1999,13,11,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
6,7,Ali Abdi,tn TUN,"MF,DF",Nice,fr Ligue 1,32,1993,22,13,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
7,8,Salis Abdul Samed,gh GHA,MF,Nice,fr Ligue 1,26,2000,18,12,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [9]:
# Ger en sammanställning av kolumner, datatyper och om det saknas värden
cleaned_df.info()

# Visar exakt hur många tomma/saknade värden (NaN) det finns i varje kolumn
print("\nSaknade värden per kolumn:")
print(cleaned_df.isna().sum())

<class 'pandas.DataFrame'>
Index: 2005 entries, 0 to 2835
Data columns (total 53 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Rk                    2005 non-null   Int64
 1   Player                2005 non-null   string
 2   Nation                2005 non-null   string
 3   Pos                   2005 non-null   string
 4   Squad                 2005 non-null   string
 5   Comp                  2005 non-null   string
 6   Age                   2005 non-null   Int64
 7   Born                  2005 non-null   Int64
 8   MP                    2005 non-null   Int64
 9   Starts                2005 non-null   Int64
 10  Min                   2005 non-null   Int64
 11  90s                   2005 non-null   Float64
 12  Gls                   2005 non-null   Int64
 13  Ast                   2005 non-null   Int64
 14  G+A                   2005 non-null   Int64
 15  G-PK                  2005 non-null   Int64
 16  PK                    2005 non-null   Int64
 17  PKatt                 2005 non-null   Int64
 18  CrdY                  2005 non-null   Int64
 19  CrdR                  2005 non-null   Int64
 20  G+A-PK                2005 non-null   Float64
 21  Sh                    2005 non-null   Int64
 22  SoT                   2005 non-null   Int64
 23  SoT%                  1859 non-null   Float64
 24  Sh/90                 2005 non-null   Float64
 25  SoT/90                2005 non-null   Float64
 26  G/Sh                  1859 non-null   Float64
 27  G/SoT                 1713 non-null   Float64
 28  PK_stats_shooting     2005 non-null   Int64
 29  PKatt_stats_shooting  2005 non-null   Int64
 30  Crs                   2005 non-null   Int64
 31  TklW                  2005 non-null   Int64
 32  Int                   2005 non-null   Int64
 33  Fld                   2005 non-null   Int64
 34  CrdY_stats_misc       2005 non-null   Int64
 35  CrdR_stats_misc       2005 non-null   Int64
 36  2CrdY                 2005 non-null   Int64
 37  Fls                   2005 non-null   Int64
 38  OG                    2005 non-null   Int64
 39  GA                    139 non-null    Int64
 40  GA90                  139 non-null    Float64
 41  SoTA                  139 non-null    Int64
 42  Saves                 139 non-null    Int64
 43  Save%                 139 non-null    Float64
 44  W                     139 non-null    Int64
 45  D                     139 non-null    Int64
 46  L                     139 non-null    Int64
 47  CS                    139 non-null    Int64
 48  CS%                   139 non-null    Float64
 49  PKatt_stats_keeper    139 non-null    Int64
 50  PKA                   139 non-null    Int64
 51  PKsv                  139 non-null    Int64
 52  PKm                   139 non-null    Int64
dtypes: Float64(10), Int64(38), string(5)
memory usage: 1.0 MB

Saknade värden per kolumn:
Rk                         0
Player                     0
Nation                     0
Pos                        0
Squad                      0
Comp                       0
Age                        0
Born                       0
MP                         0
Starts                     0
Min                        0
90s                        0
Gls                        0
Ast                        0
G+A                        0
G-PK                       0
PK                         0
PKatt                      0
CrdY                       0
CrdR                       0
G+A-PK                     0
Sh                         0
SoT                        0
SoT%                     146
Sh/90                      0
SoT/90                     0
G/Sh                     146
G/SoT                    292
PK_stats_shooting          0
PKatt_stats_shooting       0
Crs                        0
TklW                       0
Int                        0
Fld                        0
CrdY_stats_misc            0
CrdR_stats_misc            0
2CrdY                      0
Fls                        0
OG                         0
GA                      1866
GA90                    1866
SoTA                    1866
Saves                   1866
Save%                   1866
W                       1866
D                       1866
L                       1866
CS                      1866
CS%                     1866
PKatt_stats_keeper      1866
PKA                     1866
PKsv                    1866
PKm                     1866
dtype: int64

In [27]:
cleaned_df.describe()

,Rk,Age,Born,MP,Starts,Min,90s,Gls,Ast,G+A,...,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm
count,2005.0,2005.0,2005.0,2005.0,2005.0,2005.0,2005.0,2005.0,2005.0,2005.0,...,139.0,139.0,139.0,139.0,139.0,139.0,139.0,139.0,139.0,139.0
mean,1434.810973,26.495262,1998.969077,24.954613,18.705736,1664.469327,18.494314,2.268329,1.594514,3.862843,...,68.317986,9.208633,6.208633,9.064748,6.510791,26.226619,3.848921,2.971223,0.604317,0.273381
std,830.144138,4.251641,4.234169,8.011184,9.361086,791.648307,8.7971,3.28485,2.01508,4.501346,...,5.929455,6.049883,3.71342,5.52361,4.304307,13.290536,2.648253,2.105694,0.821969,0.54912
min,1.0,17.0,1983.0,5.0,1.0,446.0,5.0,0.0,0.0,0.0,...,46.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,718.0,23.0,1996.0,19.0,11.0,977.0,10.9,0.0,0.0,1.0,...,65.55,4.0,3.0,5.0,3.0,18.2,2.0,1.0,0.0,0.0
50%,1442.0,26.0,1999.0,26.0,18.0,1617.0,18.0,1.0,1.0,2.0,...,68.8,9.0,7.0,8.0,6.0,25.7,4.0,3.0,0.0,0.0
75%,2175.0,29.0,2002.0,32.0,26.0,2273.0,25.3,3.0,2.0,5.0,...,72.1,13.0,9.0,13.0,10.0,33.3,6.0,5.0,1.0,0.0
max,2836.0,42.0,2008.0,38.0,38.0,3420.0,38.0,36.0,21.0,41.0,...,82.4,27.0,18.0,23.0,19.0,80.0,12.0,9.0,3.0,3.0

In [12]:
print(cleaned_df.columns.tolist())

['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'Born', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'G+A-PK', 'Sh', 'SoT', 'SoT%', 'Sh/90', 'SoT/90', 'G/Sh', 'G/SoT', 'PK_stats_shooting', 'PKatt_stats_shooting', 'Crs', 'TklW', 'Int', 'Fld', 'CrdY_stats_misc', 'CrdR_stats_misc', '2CrdY', 'Fls', 'OG', 'GA', 'GA90', 'SoTA', 'Saves', 'Save%', 'W', 'D', 'L', 'CS', 'CS%', 'PKatt_stats_keeper', 'PKA', 'PKsv', 'PKm']

In [ ]:
# Vilka 5 spelare har gjort flest mål (Gls)?
top_scorers_query = """
    SELECT Player, Squad, Comp, Gls
    FROM cleaned_df
    ORDER BY Gls DESC
    LIMIT 5
"""

top_scorers_df = duckdb.query(top_scorers_query).to_df()
top_scorers_df

           Player            Squad                Comp  Gls
0      Harry Kane    Bayern Munich       de Bundesliga   36
1  Erling Haaland  Manchester City  eng Premier League   27
2   Kylian Mbappé      Real Madrid          es La Liga   25
3    Vedat Muriqi         Mallorca          es La Liga   23
4     Igor Thiago        Brentford  eng Premier League   22

In [18]:
# Vilka är de 5 mest effektiva unga spelarna (under 23 år) baserat på mål + assist (G+A)?
young_stars_query = """
    SELECT Player, Squad, Age, "G+A"
    FROM cleaned_df
    WHERE Age <= 23
    ORDER BY "G+A" DESC
    LIMIT 5
"""
young_stars_df = duckdb.query(young_stars_query).to_df()
young_stars_df

               Player       Squad  Age  G+A
0        Lamine Yamal   Barcelona   18   27
1        Yan Diomandé  RB Leipzig   19   20
2         Nicolás Paz        Como   21   18
3  Joaquín Panichelli  Strasbourg   23   17
4      Rasmus Højlund      Napoli   23   17

In [ ]:
# Vilken liga (Comp) är tuffast?
liga_cards_query = """
    SELECT Comp as Liga, 
           COUNT(*) as Antal_Spelare,
           ROUND(AVG(CrdY), 2) as Gula_Kort_Snitt,
           SUM(CrdR) as Totala_Röda_Kort
    FROM cleaned_df
    GROUP BY Comp
    ORDER BY Gula_Kort_Snitt DESC
"""

liga_cards_df = duckdb.query(liga_cards_query).to_df()

liga_cards_df

                 Liga  Antal_Spelare  Gula_Kort_Snitt  Totala_Röda_Kort
0          es La Liga            428             3.72              97.0
1  eng Premier League            405             3.47              44.0
2          it Serie A            440             3.05              63.0
3       de Bundesliga            359             3.05              47.0
4          fr Ligue 1            373             2.94              72.0

In [ ]:
# Djupare analys av skotteffektivitet för spelare med minst 10 mål
efficiency_query = """
    SELECT Player as Spelare, 
           Squad as Lag, 
           Comp as Liga, 
           Gls as Mål, 
           Sh as Skott_Totalt, 
           SoT as Skott_På_Mål,
           ROUND(CAST(Gls AS FLOAT) / CAST(Sh AS FLOAT), 2) as Mål_Per_Skott,
           ROUND(CAST(SoT AS FLOAT) / CAST(Sh AS FLOAT) * 100, 1) as Pricksäkerhet_Procent
    FROM cleaned_df
    WHERE Gls >= 10 AND Sh > 0
    ORDER BY Mål_Per_Skott DESC
    LIMIT 10
"""

efficiency_df = duckdb.query(efficiency_query).to_df()
efficiency_df

,Spelare,Lag,Liga,Mål,Skott_Totalt,Skott_På_Mål,Mål_Per_Skott,Pricksäkerhet_Procent
0,Jonathan Burkardt,Eintracht Frankfurt,de Bundesliga,13,41,21,0.32,51.200001
1,Harry Kane,Bayern Munich,de Bundesliga,36,119,67,0.30,56.299999
2,Borja Iglesias,Celta Vigo,es La Liga,14,46,26,0.30,56.500000
3,Ermedin Demirović,Stuttgart,de Bundesliga,12,41,22,0.29,53.700001
4,Hugo Duro,Valencia,es La Liga,10,36,14,0.28,38.900002
5,Joaquín Panichelli,Strasbourg,fr Ligue 1,16,58,31,0.28,53.400002
6,Gerard Moreno,Villarreal,es La Liga,10,39,16,0.26,41.000000
7,Igor Thiago,Brentford,eng Premier League,22,84,43,0.26,51.200001
8,Ansu Fati,Monaco,fr Ligue 1,11,43,24,0.26,55.799999
9,Viktor Gyökeres,Arsenal,eng Premier League,14,55,22,0.25,40.000000

In [ ]:
# Vilka 10 spelare blir fällda (fouled) flest gånger?
most_fouled_query = """
    SELECT Player as Spelare, Squad as Lag, Comp as Liga, Pos as Position, Fld as Fouls_Emot_Sig
    FROM cleaned_df
    ORDER BY Fld DESC
    LIMIT 10
"""

most_fouled_df = duckdb.query(most_fouled_query).to_df()
most_fouled_df

,Spelare,Lag,Liga,Position,Fouls_Emot_Sig
0,Aleix Febas,Elche,es La Liga,MF,118
1,Marco Palestra,Cagliari,it Serie A,"MF,DF",108
2,Mattia Zaccagni,Lazio,it Serie A,FW,82
3,Vinicius Júnior,Real Madrid,es La Liga,"FW,MF",81
4,Federico Bonazzoli,Cremonese,it Serie A,FW,80
5,Elliot Anderson,Nottingham Forest,eng Premier League,MF,80
6,Johan Manzambi,Freiburg,de Bundesliga,MF,78
7,Iván Romero,Levante,es La Liga,"FW,MF",77
8,Bruno Guimarães,Newcastle United,eng Premier League,MF,75
9,Issa Soumaré,Le Havre,fr Ligue 1,"FW,MF",74

In [ ]:
# Vilka spelare skjuter mest per 90 minuter?
most_shots_query = """
    SELECT Player as Spelare, Squad as Lag, Comp as Liga, "Sh/90" as Skott_Per_90min, Gls as Totala_Mål
    FROM cleaned_df
    ORDER BY "Sh/90" DESC
    LIMIT 10
"""

most_shots_df = duckdb.query(most_shots_query).to_df()
most_shots_df

           Spelare            Lag           Liga  Skott_Per_90min  Totala_Mål
0    Kylian Mbappé    Real Madrid     es La Liga             5.06          25
1      Deniz Undav      Stuttgart  de Bundesliga             4.98          19
2  Nikola Krstović       Atalanta     it Serie A             4.97          10
3     Lamine Yamal      Barcelona     es La Liga             4.66          16
4   Dušan Vlahović       Juventus     it Serie A             4.56           7
5       Harry Kane  Bayern Munich  de Bundesliga             4.51          36
6       Moise Kean     Fiorentina     it Serie A             4.33           8
7    Donyell Malen           Roma     it Serie A             4.29          14
8  Mason Greenwood      Marseille     fr Ligue 1             4.24          16
9         Raphinha      Barcelona     es La Liga             4.24          13

In [ ]:
# Vilka spelare har fått flest röda kort och hur många matcher har de spelat?
most_reds_query = """
    SELECT Player as Spelare, 
           Squad as Lag, 
           Comp as Liga, 
           MP as Matcher,
           CrdR as Röda_Kort, 
           CrdY as Gula_Kort
    FROM cleaned_df
    WHERE CrdR > 0
    ORDER BY CrdR DESC, CrdY DESC, MP ASC
    LIMIT 10
"""


most_reds_df = duckdb.query(most_reds_query).to_df()
most_reds_df

,Spelare,Lag,Liga,Matcher,Röda_Kort,Gula_Kort
0,Federico Viñas,Oviedo,es La Liga,33,3,7
1,Cristian Romero,Tottenham Hotspur,eng Premier League,23,2,11
2,Dominik Kohr,Mainz 05,de Bundesliga,29,2,11
3,Djené,Getafe,es La Liga,34,2,10
4,Nobel Mendy,Rayo Vallecano,es La Liga,24,2,9
5,Wesley Fofana,Chelsea,eng Premier League,25,2,9
6,Pathé Ciss,Rayo Vallecano,es La Liga,29,2,9
7,Niklas Stark,Werder Bremen,de Bundesliga,14,2,8
8,Mariano Troilo,Parma,it Serie A,21,2,8
9,Thilo Kehrer,Monaco,fr Ligue 1,28,2,8

In [ ]:
# Vilka försvarare gör flest mål?
scoring_defenders_query = """
    SELECT Player as Spelare, Squad as Lag, Comp as Liga, Pos as Position, Gls as Mål, MP as Matcher
    FROM cleaned_df
    WHERE Pos LIKE '%DF%'
    ORDER BY Gls DESC
    LIMIT 10
"""

scoring_defenders_df = duckdb.query(scoring_defenders_query).to_df()
scoring_defenders_df

,Spelare,Lag,Liga,Position,Mål,Matcher
0,Virgil van Dijk,Liverpool,eng Premier League,DF,6,38
1,Carlos Romero,Espanyol,es La Liga,DF,6,36
2,Maximilian Mittelstädt,Stuttgart,de Bundesliga,"DF,MF",6,32
3,Dominik Szoboszlai,Liverpool,eng Premier League,"MF,DF",6,36
4,Luka Vušković,Hamburger SV,de Bundesliga,DF,6,28
5,Nico Schlotterbeck,Dortmund,de Bundesliga,DF,5,28
6,Ramy Bensebaini,Dortmund,de Bundesliga,DF,5,21
7,Nico O’Reilly,Manchester City,eng Premier League,"DF,MF",5,34
8,Strahinja Pavlović,Milan,it Serie A,DF,5,34
9,Alimami Gory,Paris FC,fr Ligue 1,"MF,DF",5,24